---
name: Release Process

on:
  repository_dispatch:
    types: [trigger-release]

# Restrict permissions to minimum required
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use a personal access token with repo scope instead of GITHUB_TOKEN
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline || yarn install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: ${{ github.event.client_payload.publish_to_npm && 'yarn release' || '' }}
          title: 'Version Packages'
          commit: 'Version Packages'
        env:
          # Use personal access token instead of GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Only run these steps if we published a new version
      - name: Build Storybook
        if: steps.changesets.outputs.published == 'true'
        run: yarn build-storybook

      - name: Deploy to GitHub Pages
        if: steps.changesets.outputs.published == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          branch: gh-pages
